### ISSUE TITLE
Translating API docs without context is confusing

### ISSUE THREAD

**Issue by runinspring** [electron/electron-i18n#58]
https://crowdin.com/project/electron/  
in this website , content/en/api  is empty, how can i create a new file

**Comment by zeke** [comment]
Hi @runinspring. You shouldn't need to create any new files. Please try the following:

- Visit https://crowdin.com/project/electron
- Log in using your GitHub account.
- Pick a locale, e.g. https://crowdin.com/project/electron/zh-CN#
- Pick a file and you'll see a window for translating its strings:

![screen shot 2017-08-07 at 9 47 53 am](https://user-images.githubusercontent.com/2289/29036739-80547326-7b55-11e7-90cc-f97c4d977bf1.png)

**Comment by runinspring** [comment]
![image](https://user-images.githubusercontent.com/7044793/29055681-6c955022-7c30-11e7-9ff3-f32e80e75fb5.png)
but the api  folder contains no files

**Comment by runinspring** [comment]
![image](https://user-images.githubusercontent.com/7044793/29061650-51d790a8-7c51-11e7-9254-1040c8a3a712.png)
the api-descriptions.yml，It's hard to see which API is being translated, and there is no md file , where can I see the results of the translation ?

**Comment by zeke** [comment]
Ah I see the confusion.

The `api-descriptions.yml` actually contains all of the English-language source content from the API docs that needs to be translated. We don't want to translate api names, method names, arguments, properties, data types, etc. We really just want the descriptions of these things translated, and that's what is present in this file. Eventually we will be using localized [structured API data](https://electron.atom.io/blog/2016/09/27/api-docs-json-schema) to display API docs on the site, rather than just copying over the raw markdown docs from electron/electron like we do now.

In your screenshot above, you can see the context `app.methods.quit.description`.

I understand though that it may be hard to translate without the full context of the API document. Please give it a try and let us know if it's manageable.

> where can I see the results of the translation ?

The translated content is not yet displayed anywhere. We are currently in the process of [migrating our website from Jekyll to Node](https://github.com/electron/electron.atom.io/pull/758) to make it possible for us to display localized content on the site. We are not there yet, but we are working on it. Please subscribe to that issue for updates.

**Comment by runinspring** [comment]
Thx，I will try to translate the api-descriptions.yml

**Comment by zeke** [comment]
I have updated the issue title and will leave it open. After you've translating some API descriptions please leave your feedback here. I'm open to changing this process if what we have now does not work. Thanks!

**Comment by runinspring** [comment]
1）I must read the MD file when translation. But this is acceptable.
2）
![image](https://user-images.githubusercontent.com/7044793/29104826-610b1496-7cfb-11e7-91e6-70d3698e4a66.png)
There is no paragraph style in api-descriptions.yml, which brought some translation difficulties.
And when you displayed the translated content , Whether it can be automatically segmented or not?
If not，it's hard to read
3）
![image](https://user-images.githubusercontent.com/7044793/29104850-93b918de-7cfb-11e7-968b-24636968dd09.png)

In MD file, you can see the key word,but it's disappeared in api-descriptions.yml

**Comment by zeke** [comment]
Thanks for the info. I've opened an issue here to address it: https://github.com/electron/electron-docs-linter/issues/99

**Comment by zeke** [comment]
Fixed by https://github.com/electron/electron-i18n/issues/67
